"use strict";
var __importDefault = (this && this.__importDefault) || function (mod) {
    return (mod && mod.__esModule) ? mod : { "default": mod };
};
Object.defineProperty(exports, "__esModule", { value: true });
const express_1 = __importDefault(require("express"));
const userUpdate_1 = __importDefault(require("./routes/userUpdate"));
const authentication_1 = __importDefault(require("./routes/authentication"));
const userOTP_1 = __importDefault(require("./routes/userOTP"));
const products_1 = __importDefault(require("./routes/products"));
const userDetails_1 = __importDefault(require("./routes/userDetails"));
const siteData_1 = __importDefault(require("./routes/siteData"));
const productCheckout_1 = __importDefault(require("./routes/productCheckout"));
const cartCheckout_1 = __importDefault(require("./routes/cartCheckout"));
const homeData_1 = __importDefault(require("./routes/homeData"));
const support_1 = __importDefault(require("./routes/support"));
const rateLimit_1 = require("./middleware/rateLimit");
const router = express_1.default.Router();
router.use('/user/signup', rateLimit_1.authRateLimiterMiddleware);
router.use('/user/signin', rateLimit_1.authRateLimiterMiddleware);
router.use('/user/send-forgot-otp', rateLimit_1.authRateLimiterMiddleware);
router.use('/user/reset-password', rateLimit_1.authRateLimiterMiddleware);
router.use('/auth/google', rateLimit_1.authRateLimiterMiddleware);
router.use('/native/auth/google', rateLimit_1.authRateLimiterMiddleware);
router.use('/', authentication_1.default);
router.use('/update', userUpdate_1.default);
router.use('/', userOTP_1.default);
router.use('/', products_1.default);
router.use('/', userDetails_1.default);
router.use('/', siteData_1.default);
router.use('/', productCheckout_1.default);
router.use('/', cartCheckout_1.default);
router.use('/', homeData_1.default);
router.use('/', support_1.default);
exports.default = router;
